from pathlib import Path

# Default paths
DEFAULT_DATASET_PATH = (YOUR_DATASET_DIR)
DEFAULT_MODEL_NAME = (YOUR_CUSTOM_MODEL)
DEFAULT_DB_DIR = (YOUR_VECTOR_DB)
DEFAULT_CLEAN_DIR = (YOUR_CLEAN_TRANSCRIPT_data)
DEFAULT_N_RESULTS = 5

# Metric thresholds
METRIC_THRESHOLD = 0.7